# Site settings
title: 咖啡不苦
description: > # code is poem
baseurl: "" 
url: "http://laichendong.com" 

# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
includes:    ./_includes
data_source: ./_data
collections: null

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
